### PR TITLE
Share Kit for Angular

### LINKED ISSUE #41: Share Kit for Angular.js
Bloom is looking for great developers to help us build out the Bloom Share Kit ecosystem. Share Kit is the mechanism used for registering or authenticating on third-party websites and apps using your BloomID, providing individuals with a secure, encrypted way to access services without sharing private data, all without the need for usernames and passwords.

Share Kit can also be used to ask users for verified data where needed. For example, you could ask for a verified mobile phone number to send them SMS messages, or ask for verified data to comply with Know Your Client (KYC) regulations. It’s as easy as scanning a QR code or tapping a button!

Here is an example of how it works: https://www.youtube.com/watch?v=5bcSxy4CnfM

We have DOM and React-based libraries. Now we’re turning to the community to help us build and maintain the following Share Kit libraries. This bounty is worth 500 DAI and needs your help!

# Share Kit Library Conversion to Angular.js Bounty

### General:
- Must expose all necessary types (if language has type system)
  - Types available [here](https://github.com/hellobloom/share-kit/blob/master/src/types.ts)
  - Interfaces available [here](https://github.com/hellobloom/share-kit/blob/master/src/util.ts) 
  - Please ensure you read and adhere to the comments in the code
- Must have adequate tests to cover the features implemented
  - Existing tests:
    - [renderRequestElement.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/renderRequestElement.test.ts) 
    - [renderRequestButton.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/elements/renderRequestButton.test.ts) 
    - [renderRequestQRCode.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/elements/renderRequestQRCode.test.ts) 
    - [util.test.ts](https://github.com/hellobloom/share-kit/blob/master/src/util.test.ts)
- Use of a UI component framework similar to [Storybook](https://storybook.js.org/) is preferred

### Share Kit Verification Implementation Requirements:
Must expose all the same functions in [share-kit/src/utils](https://github.com/hellobloom/share-kit/blob/master/src/util.ts) and [share-kit/src/txUtils](https://github.com/hellobloom/share-kit/blob/master/src/txUtils.ts) 

### Desktop and Mobile (e.g. Angular, Vue, Xamarin):
- Can be based on existing [share-kit](https://github.com/hellobloom/share-kit) library if applicable
- Detects platform and renders a button on mobile, or QR code on desktop/laptop
  - Must also allow for override via configuration
  - Button should be default for mobile devices
- QR Code:
  - Appends the query param `share-kit-from=qr` to the provided requestData.url
  - Draws a QR code with the base64 encoded requestData
    - Desktop-based demo [available here](https://bloom.co/identity) 
  - Offer customization of:
    - Foreground and background color
    - Size
    - Logo (image, width, height, opacity) and whether or not it should be visible
    - error correction level
    - Desktop-based demo [available here](https://bloom.co/docs/share-kit/demo) 
  - Default the options to the same values in the base share-kit implementation
    - Default options [available here](https://github.com/hellobloom/share-kit#qroptions) 
  - Library must have the ability to update and remove the QR code after initial rendering
    - If applicable to the platform
- Bloom uses [Bowser](https://github.com/lancedikson/bowser) to detect `UserAgent`; you can use this library or a similar one to determine whether the button or QR code should be displayed

## Relevant GitHub repositories:
- [Share Kit](https://github.com/hellobloom/share-kit) 
- [Receive Kit](https://github.com/hellobloom/receive-kit) 
- [Share Kit React](https://github.com/hellobloom/share-kit-react) 
- [Bloom Starter](https://github.com/hellobloom/bloom-starter)

### PR DESCRIPTION
**Pull request by pbteja1998**
Resolves [#41](https://github.com/hellobloom/share-kit/issues/41)

### CODE REVIEW

**Comment by JaceHensley** [comment]
hey @pbteja1998 this seems like a "app" and not a component library. The component should be the `src/`. What's in `src/` right now is boilerplate for an application. See how this library is set up: https://github.com/angular/components/tree/master/src/material. We'll want something like this. Thanks!

**Comment by pbteja1998** [comment]
@JaceHensley Yes the library is present in [projects/share-kit-angular-lib](https://github.com/pbteja1998/share-kit-angular/tree/master/projects/share-kit-angular-lib)

**Comment by pbteja1998** [comment]
Do you want to have just that folder in the repo?

**Comment by pbteja1998** [comment]
Right now in order to build the package, you have to do `ng build share-kit-angular-lib` 

To publish the package, 
```
cd dist/share-kit-angular-lib
npm publish 
```

**Comment by JaceHensley** [comment]
Right, that should be the main thing. This doesn't need all that other boilerplate. It's just a component lib that people should be able to:

```
// Install
npm install @bloomprotocol/share-kit-angular

// Import
import {RequestElement} from '@bloomprotocol/share-kit-angular'
```

**Comment by pbteja1998** [comment]
Ok, I will change the project structure accordingly. Till then, if there are any changes in the library, please tell me.

**Comment by pbteja1998** [comment]
@JaceHensley I changed the project structure. Please tell me if this ok.

- With this structure it will be easy to add any new components(or modules) in the future if necessary using cli
- Now `src` folder only has `storybook stories`
- `projects` has all the components (Right now only `request-element`)
- Testing, Building & Publishing details are added to `README`

Main code is present [here](https://github.com/pbteja1998/share-kit-angular/blob/master/projects/request-element/src/lib/request-element.component.ts)

**Comment by pbteja1998** [comment]
@JaceHensley is there anything else that needs to be changed?

**Comment by dereksilva** [comment]
@pbteja1998 It's a holiday in the USA today, but I'll make sure we get back to you by tomorrow. Thanks!

**Comment by pbteja1998** [comment]
@dereksilva No problem. Thanks.

**Comment by JaceHensley** [comment]
Could you add a story to show to updating of props like this [one](https://github.com/hellobloom/share-kit-react/blob/master/.storybook/index.js#L34)? And have the logo story match this [one](https://github.com/hellobloom/share-kit-react/blob/master/.storybook/index.js#L30) where the logo visibility can be toggled with a checkbox? This is looking really great!

**Comment by pbteja1998** [comment]
OK, sure. Everything else is fine?

**Comment by dereksilva** [comment]
@pbteja1998 We're reviewing the work now and will get back to you as soon as possible with additional feedback.

**Comment by pbteja1998** [comment]
@JaceHensley Checkout the storybook now. I have used `storybook-addon-knobs`. So now, you can dynamically change any prop.

**Comment by edhedges** [comment]
@pbteja1998 We've got a few questions as we're not well-versed angular.

1. Why is `src` used for stories and `projects` for the source of the component?
2. I followed your directions in the README to publish an initial version to npm https://www.npmjs.com/package/@bloomprotocol/share-kit-angular but when I install it with `npm install --save @bloomprotocol/share-kit-angular` it doesn't install the required `npm install --save @bloomprotocol/share-kit` dependency, is that intended? On this same note, this package should not be private, so could you remove the `"private": true,` line from the root `package.json`.

Otherwise, this looks good! The story with the knobs is really useful and I was able to get it working in an external project by following the README docs. The `patch-webpack.js` thing is quite unfortunate. Where should that be addressed? Is it an Angular bug or something else?

**Comment by pbteja1998** [comment]
@edhedges 

- Unlike in frameworks like `React`, In Angular, we can create everything(application, class, component, library,...) using [angular-cli](https://angular.io/cli/generate). I have [created the library using angular-cli](https://angular.io/guide/creating-libraries) and this creates the `projects` folder where all the libraries will be present. I don't think this is easy to override as this also makes some changes in `angular.json` and some other files.

- I used `npx -p @storybook/cli sb init --type angular` to configure storybook as given in the [official docs](https://storybook.js.org/docs/guides/guide-angular/). It automatically added an initial story in the `src/stories` directory. 

- I added `@bloomprotocol/share-kit` as a [Peer Dependency](https://nodejs.org/es/blog/npm/peer-dependencies/) in [library's package.json](https://github.com/pbteja1998/share-kit-angular/blob/master/projects/request-element/package.json). That's why it is not being installed automatically. I removed that in `peerDependencies` and added it to `dependencies`. Now it will be installed automatically. Please tell me if this change needs to be reverted.

- Every angular library generated by `angular-cli` has its own `package.json`. This library's `package.json` is [here](https://github.com/pbteja1998/share-kit-angular/blob/master/projects/request-element/package.json). I just found out that [scoped packages](https://docs.npmjs.com/misc/scope) are published as `private` by default. I added `"publishConfig": { "access": "public"}` to [package.json](https://github.com/pbteja1998/share-kit-angular/blob/master/projects/request-element/package.json). Now when you are publishing, it will be published as a public package.

- I think that the `patch-webpack.js` thing is angular bug(specifically I think when trying to use `crypto` package in an angular browser application). When you create a new angular application using `ng new`, you will encounter that error. So after a new application is created, that patch should be applied.

**Comment by edhedges** [comment]
@pbteja1998 Thank you for addressing our feedback and for answering my questions thoroughly! I am going to put the ball in @dereksilva's court now to get things wrapped up.

**Pull request merged**
